[supabase]
url = "https://vdjzpwierxgrhtbbpzqk.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkanpwd2llcnhncmh0YmJwenFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0MzA0NDEsImV4cCI6MjA5MzAwNjQ0MX0.Z-gyWX6TZeZB66H4pR770IZNh4kcgcTxJz-XhgKVcwU"

[meta_ads]
app_id = "1395117575703914"
access_token = "EAAT02hZBFDWoBRVBF1jceTGCTxvVmee2mvHmdQrZCSpAxXHFWgAIPBZBWG3os8q9JbxJuuP20Y0s0MdwLgOIVsTFF1C1mDfIYl4hJS3YZCAhaYzZAZAJcww049ZA4FjOcjqOsM0qwjOvalqkVI9ZCrxy0VI1PQEocJoZBqZBRcPuQxsrYEVLJM90m7HHhw8YJX"
